# Generated by Django 5.2.3 on 2025-06-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employerprofile_jobseekerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('jobseeker', 'Job Seeker'), ('employer', 'Employer')], default='jobseeker', max_length=20),
        ),
    ]
