# Generated by Django 5.2.3 on 2025-06-20 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='job_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
